# Generated by Django 5.1.7 on 2025-05-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, upload_to='classmates_photos/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название программы')),
                ('link', models.URLField(verbose_name='Ссылка на программу')),
                ('description', models.TextField(verbose_name='Описание')),
                ('skills', models.TextField(verbose_name='Чему научусь')),
                ('advantages', models.TextField(verbose_name='Преимущества программы')),
                ('prospects', models.TextField(verbose_name='Перспективы после обучения')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('role', models.CharField(choices=[('head', 'Академический руководитель'), ('manager', 'Менеджер программы')], max_length=10, verbose_name='Роль')),
                ('photo', models.ImageField(blank=True, upload_to='managers_photos/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, upload_to='student_photos/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('resume', models.FileField(blank=True, upload_to='resumes/', verbose_name='Резюме')),
            ],
        ),
    ]
