# Generated by Django 5.1.7 on 2025-05-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalprogram',
            old_name='link',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='classmate',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='classmate',
            name='photo',
            field=models.ImageField(upload_to='classmates/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='advantages',
            field=models.TextField(verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='prospects',
            field=models.TextField(verbose_name='Перспективы'),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='programmanager',
            name='photo',
            field=models.ImageField(upload_to='managers/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(upload_to='profile/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(upload_to='resumes/', verbose_name='Резюме'),
        ),
    ]
