# Generated by Django 5.1.7 on 2025-05-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbcModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255, verbose_name='ФИО')),
                ('x', models.FloatField(default=0.0, verbose_name='Значение X')),
                ('y', models.FloatField(default=0.0, verbose_name='Значение Y')),
                ('final_score', models.FloatField(default=0.0, help_text='Автоматически рассчитывается при сохранении', verbose_name='Итоговая оценка (0.5 * X + 0.5 * Y)')),
                ('result', models.CharField(default='Результат не определён', help_text='Текстовое описание результата', max_length=255, verbose_name='Результат вычисления')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения (save)')),
            ],
            options={
                'verbose_name': 'Итоговая оценка',
                'verbose_name_plural': 'Итоговые оценки',
                'ordering': ('-pk',),
            },
        ),
    ]
