# Generated by Django 5.1.7 on 2025-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodrovaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abcmodel',
            options={'ordering': ('-pk',), 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterField(
            model_name='abcmodel',
            name='current_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='abcmodel',
            name='final_score',
            field=models.FloatField(default=0.0, help_text='Результат вычислений', verbose_name='Итоговая оценка (0.5 * X + 0.5 * Y)'),
        ),
        migrations.AlterField(
            model_name='abcmodel',
            name='result',
            field=models.CharField(default='Результат не определён', help_text='Например: ошибка или пояснение', max_length=255, verbose_name='Описание результата'),
        ),
    ]
